const ERROR_CODE = {
  // Server
  SUCCESS: 0,
  SERVER_ERROR: -1,

  // Authenticate
  TOKEN_REQUIRED: 1000,
  TOKEN_NOTFOUND: 1001,
  TOKEN_INVALID: 1002,

  // Calendar
  CALENDAR_NOT_FOUND: 1100,

  // Events
  EVENT_INPUT_REQUIRED: 1200,
  EVENT_INPUT_INVALID: 1201,
  EVENT_TIME_INVALID: 1202,
  EVENT_REMINDER_TIME_INVALID: 1203,
  EVENT_REMINDER_OPTION_INVALID: 1204,
};

module.exports = ERROR_CODE;
